name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version if tag
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Print extracted version
        run: echo "Version is $VERSION"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/melotts:latest .
          if [[ -n "${{ env.VERSION }}" ]]; then
            docker tag ${{ secrets.DOCKER_USERNAME }}/melotts:latest ${{ secrets.DOCKER_USERNAME }}/melotts:${{ env.VERSION }}
          fi

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/melotts:latest
          if [[ -n "${{ env.VERSION }}" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/melotts:${{ env.VERSION }}
          fi